### ISSUE TITLE
Wrong first accordion content height wity tinymce 4.3.8

### ISSUE THREAD

**Issue by azhidkov** [josh18/TinyMCE-FontAwesome-Plugin#32] opened 2016-04-15 14:48 UTC
When I open window at first time, first accordion content has wrong height (see screenshot). This line ```firstAccordionContent.getBoundingClientRect().height``` return 44px instead of 435px.

When I close and then again open first accordion item content height is right. 

![wrong_first_height_creenshot](https://cloud.githubusercontent.com/assets/3435397/14565072/0c7a692a-0332-11e6-9eee-d7076515797e.png)

**Comment by josh18** [comment] 2016-04-16 04:40
Strange, what browser?

**Comment by azhidkov** [comment] 2016-04-20 07:03
Hello, @josh18 

I'm using Google Chrome Version 52.0.2712.0 canary (64-bit).

Previously I've used tinymce 4.1.3 with your plugin and everything works fine, and this strange behaviour started after I recently updated tinymce to 4.3.8 version.

**Comment by webdev20** [comment] 2016-05-01 23:02
I commented this line out and it solves the problem:
`firstAccordionContent.style.height = nextHeight + 'px';`

**Comment by josh18** [comment] 2016-05-01 23:42
Sorry I haven't had much time lately. I assume it's caused by the newer version of TinyMCE. It's probably detecting the initial height before it has fully loaded. If you do what @webdev20 suggested I assume the first animation (accordion closing) doesn't work?

**Comment by josh18** [comment] 2016-05-02 03:40
Sorry I can't reproduce this. Have you tried any other browsers? It would be good if you could test on standard Chrome and / or incognito mode. Can you set me up a demo just in case it is your web environment?

**Comment by josh18** [comment] 2016-06-01 21:15
Closing for now as I can't reproduce the bug. If it is still a problem feel free to reopen this issue but I can't fix it unless I have more info.

**Closed by josh18** 2016-06-01 21:15 UTC
